import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { cn } from '~lib/utils'

const euclidFlex = localFont({
	src: './fonts/EuclidFlexRegular.ttf',
	variable: '--font-euclid-flex',
})

interface Props {
	children: React.ReactNode
}

function Layout({ children }: Props) {
	return (
		<html lang='en'>
			<body className={cn('antialiased layout', euclidFlex)}>
				{children}
			</body>
		</html>
	)
}

export default Layout

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
